export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL ";
export const UPDATED_ID = "UPDATED_ID";
export const UPDATED_POSTS = "UPDATED_POSTS";
export const UPDATE_ISSUE = "UPDATE_ISSUE";
export const SET_ISLOADING = "SET_ISLOADING";
